RVBOOT_VERSION = 1.0
RVBOOT_SITE = https://s3br.bld.zone
RVBOOT_SOURCE = pico-rvboot.tar.gz
RVBOOT_INSTALL_IMAGES = YES

RVBOOT_UBOOT_MAKE = $(BR2_MAKE)
RVBOOT_UBOOT_DIR = $(@D)/u-boot
RVBOOT_UBOOT_CFG = $(BR2_PACKAGE_RVBOOT_BOARD_DEFCONFIG)
RVBOOT_UBOOT_CFG_FRAGMENT = $(BR2_PACKAGE_RVBOOT_CONFIG_FRAGMENT_FILES)
RVBOOT_UBOOT_COMPILE_MAKE =
RVBOOT_UBOOT_COMPILE_MAKE = $(RVBOOT_UBOOT_DIR)/make.sh
RVBOOT_CROSS_COMPILE = $(TARGET_CROSS)
DOWNLOAD_SRC_BIN := *_download_v*.bin
IDBLOCK_SRC_BIN := *_idblock_v*.img
DOWNLOAD_BIN := download.bin
IDBLOCK_IMG := idblock.img

HOST_RVBOOT_MAKE_OPTS = HOSTCC="$(HOSTCC)" \
	HOSTCFLAGS="$(HOST_CFLAGS)" \
	HOSTLDFLAGS="$(HOST_LDFLAGS)" \
	CONFIG_EFI_HAVE_CAPSULE_SUPPORT=y

HOST_RVBOOT_MAKE_OPTS += CONFIG_FIT=y CONFIG_MKIMAGE_DTC_PATH=dtc
HOST_RVBOOT_DEPENDENCIES += host-dtc

#SYSDRV_UBOOT_RKBIN_OVERLAY_INI :=
ifneq ($(SYSDRV_UBOOT_RKBIN_OVERLAY_INI),)
	RVBOOT_UBOOT_COMPILE_MAKE_OPTS ?= --spl-new $(SYSDRV_UBOOT_RKBIN_OVERLAY_INI)
else
	RVBOOT_UBOOT_COMPILE_MAKE_OPTS ?= --spl-new
endif

define RVBOOT_BUILD_CMDS
	echo "build uboot"
	echo "$(BR2_PACKAGE_RVBOOT_CONFIG_FRAGMENT_FILE)"
	echo "$(BR2_PACKAGE_RVBOOT_CONFIG_FRAGMENT_FILE_NAME)"
	cp -fv $(BR2_PACKAGE_RVBOOT_CONFIG_FRAGMENT_FILE) $(RVBOOT_UBOOT_DIR)/configs/
	$(RVBOOT_UBOOT_MAKE) -C $(RVBOOT_UBOOT_DIR) $(RVBOOT_UBOOT_CFG) $(BR2_PACKAGE_RVBOOT_CONFIG_FRAGMENT_FILE_NAME)
	pushd $(RVBOOT_UBOOT_DIR);$(RVBOOT_UBOOT_COMPILE_MAKE) $(RVBOOT_UBOOT_COMPILE_MAKE_OPTS) CROSS_COMPILE=$(RVBOOT_CROSS_COMPILE) || exit 1;popd
	
endef

ifeq ($(UBOOT_NAND_PAGE_SIZE),4096)
COPY_ADDITIONAL = $(RKBIN_DIR)/tools/programmer_image_tool -i $(RVBOOT_UBOOT_DIR)/$(DOWNLOAD_SRC_BIN) -b $(UBOOT_NAND_BLOCK_SIZE) -p 4 -2 -t spinand -o $(SYSDRV_DIR_OUT_IMAGE) || exit 1
else
COPY_ADDITIONAL = cp -fv $(RVBOOT_UBOOT_DIR)/$(IDBLOCK_SRC_BIN) $(BINARIES_DIR)/$(IDBLOCK_IMG)
endif

define RVBOOT_INSTALL_IMAGES_CMDS
	$(COPY_ADDITIONAL)
	cp -fv $(RVBOOT_UBOOT_DIR)/$(DOWNLOAD_SRC_BIN) $(BINARIES_DIR)/$(DOWNLOAD_BIN)
	cp -fv $(RVBOOT_UBOOT_DIR)/uboot.img $(BINARIES_DIR)/uboot.img
endef

$(eval $(generic-package))